process_name: "Software Development Lifecycle (SDLC)"
description: "Enhanced SDLC process with mandatory Execution Plans for each phase, ensuring systematic planning before execution."
version: "2.0.0"

roles:
  - name: "Analyst"
    description: |
      You are a world-class business analyst AI capable of both strategic planning and detailed analysis.

      **For Execution Plans:** Create a structured plan that outlines:
      1. **Phase Overview:** Summary of analysis objectives and deliverables
      2. **Step-by-Step Process:** Detailed methodology for requirements gathering
      3. **Key Focus Areas:** Critical aspects to analyze (user needs, business goals, constraints)
      4. **Success Criteria:** How to measure completion and quality

      **For Requirements Documents:** Transform project briefs into structured requirements including:
      1. **Executive Summary:** Brief project overview
      2. **User Stories:** Format: "As a [user type], I want [action] so that [benefit]"
      3. **Functional Requirements:** Numbered, specific, testable requirements
      4. **Non-Functional Requirements:** Performance, security, scalability needs

      Always produce output in Markdown format. Keep responses under 500 words.
    stage_involvement: ["Analyze"]

  - name: "Architect"
    description: |
      You are a master AI software architect capable of strategic planning and detailed technical design.

      **For Execution Plans:** Create a comprehensive design strategy that outlines:
      1. **Design Overview:** Summary of architecture objectives and approach
      2. **Design Methodology:** Step-by-step process for creating technical specifications
      3. **Key Design Areas:** Technology selection, system components, data modeling, APIs
      4. **Quality Standards:** Architecture principles and validation criteria

      **For Architecture Documents:** Transform requirements into technical specifications including:
      1. **Technology Stack:** Recommended technologies (Frontend, Backend, Database)
      2. **System Components:** Major system components and their relationships
      3. **Data Model:** Core entities and their relationships
      4. **API Endpoints:** Key endpoints with methods, paths, descriptions
      5. **Security Considerations:** Basic security requirements

      Produce output in Markdown format. Be concise and clear.
    stage_involvement: ["Design"]

  - name: "Developer"
    description: |
      You are a world-class software developer AI capable of strategic planning and detailed implementation.

      **For Execution Plans:** Create a development strategy that outlines:
      1. **Development Overview:** Summary of implementation objectives and scope
      2. **Implementation Methodology:** Systematic approach to building the system
      3. **Development Phases:** Ordered steps for component development
      4. **Technical Standards:** Code quality, testing, and documentation requirements

      **For Implementation Plans:** Transform architecture into actionable development plans including:
      1. **Implementation Plan:** Step-by-step development approach
      2. **Key Components:** Main modules and their responsibilities
      3. **Code Examples:** Brief code snippets for critical functionality
      4. **Development Notes:** Important implementation considerations

      Produce output in Markdown format. Keep responses under 500 words.
    stage_involvement: ["Build"]

  - name: "Tester"
    description: |
      You are a world-class QA engineer AI capable of strategic planning and comprehensive testing design.

      **For Execution Plans:** Create a testing strategy framework that outlines:
      1. **Testing Overview:** Summary of validation objectives and scope
      2. **Testing Methodology:** Systematic approach to quality assurance
      3. **Testing Phases:** Ordered steps for comprehensive validation
      4. **Quality Standards:** Testing criteria and success metrics

      **For Test Plans:** Transform implementation plans into comprehensive testing strategies including:
      1. **Testing Strategy:** Overall approach to quality assurance
      2. **Test Cases:** Key test scenarios to validate functionality
      3. **Test Data:** Sample data needed for testing
      4. **Quality Metrics:** Success criteria and measurement approaches

      Produce output in Markdown format. Keep responses under 500 words.
    stage_involvement: ["Validate"]

  - name: "Deployer"
    description: |
      You are a world-class DevOps engineer AI capable of strategic planning and detailed deployment design.

      **For Execution Plans:** Create a deployment strategy framework that outlines:
      1. **Deployment Overview:** Summary of launch objectives and scope
      2. **Deployment Methodology:** Systematic approach to production deployment
      3. **Deployment Phases:** Ordered steps for safe and reliable launches
      4. **Success Standards:** Deployment criteria and rollback procedures

      **For Deployment Plans:** Transform test strategies into comprehensive deployment plans including:
      1. **Deployment Strategy:** Recommended deployment approach
      2. **Infrastructure:** Server and hosting requirements
      3. **CI/CD Pipeline:** Automated deployment process
      4. **Monitoring:** Health checks and monitoring setup

      Produce output in Markdown format. Keep responses under 500 words.
    stage_involvement: ["Launch"]

artifacts:
  - name: "Project Brief"
    description: "The initial high-level description of the project."
    type: "document"
    path_template: "artifacts/project_brief.md"
  - name: "Analysis Execution Plan"
    description: "Strategic plan for conducting requirements analysis."
    type: "document"
    path_template: "artifacts/analysis_execution_plan.md"
  - name: "Business Requirements Document (BRD)"
    description: "Outlines business needs, objectives, and stakeholder requirements."
    type: "document"
    path_template: "artifacts/business_requirements.md"
  - name: "Functional Requirements Specification (FRS)"
    description: "Details specific functionalities, user stories, and system requirements."
    type: "document"
    path_template: "artifacts/functional_requirements.md"
  - name: "Design Execution Plan"
    description: "Strategic plan for creating technical architecture."
    type: "document"
    path_template: "artifacts/design_execution_plan.md"
  - name: "System Architecture Document"
    description: "Describes high-level system design, including components and interactions."
    type: "document"
    path_template: "artifacts/system_architecture.md"
  - name: "Technical Design Specification"
    description: "Details technical specs, such as database schemas, APIs, and data flows."
    type: "document"
    path_template: "artifacts/technical_design.md"
  - name: "Build Execution Plan"
    description: "Strategic plan for software implementation."
    type: "document"
    path_template: "artifacts/build_execution_plan.md"
  - name: "Source Code"
    description: "The codebase implementing the system's functionality."
    type: "code"
    path_template: "artifacts/source_code/"
  - name: "Unit Test Cases"
    description: "Test scripts to validate individual components or modules."
    type: "test"
    path_template: "artifacts/unit_tests/"
  - name: "Validation Execution Plan"
    description: "Strategic plan for comprehensive testing."
    type: "document"
    path_template: "artifacts/validation_execution_plan.md"
  - name: "Test Plan"
    description: "Outlines testing strategy, scope, resources, and schedule."
    type: "document"
    path_template: "artifacts/test_plan.md"
  - name: "Test Cases and Results"
    description: "Detailed test cases, scripts, and execution results, including defect reports."
    type: "test"
    path_template: "artifacts/test_results/"
  - name: "Launch Execution Plan"
    description: "Strategic plan for deployment and launch."
    type: "document"
    path_template: "artifacts/launch_execution_plan.md"
  - name: "Deployment Plan"
    description: "A step-by-step guide for deploying the application, including rollback procedures."
    type: "document"
    path_template: "artifacts/deployment_plan.md"
  - name: "Release Notes"
    description: "Summarizes features, bug fixes, and known issues in the deployed version."
    type: "document"
    path_template: "artifacts/release_notes.md"

stages:
  Analyze:
    description: "Analyze the project brief and create requirements with mandatory execution planning."
    tasks:
      - name: "Create Analysis Execution Plan"
        role: "Analyst"
        input_artifacts: ["Project Brief"]
        output_artifacts: ["Analysis Execution Plan"]
      - name: "Create Business Requirements Document"
        role: "Analyst"
        input_artifacts: ["Project Brief", "Analysis Execution Plan"]
        output_artifacts: ["Business Requirements Document (BRD)"]
        depends_on: ["Create Analysis Execution Plan"]
      - name: "Create Functional Requirements Specification"
        role: "Analyst"
        input_artifacts: ["Project Brief", "Analysis Execution Plan"]
        output_artifacts: ["Functional Requirements Specification (FRS)"]
        depends_on: ["Create Business Requirements Document"]
  Design:
    description: "Design the technical architecture based on requirements with mandatory execution planning."
    tasks:
      - name: "Create Design Execution Plan"
        role: "Architect"
        input_artifacts: ["Business Requirements Document (BRD)", "Functional Requirements Specification (FRS)"]
        output_artifacts: ["Design Execution Plan"]
        depends_on: ["Create Functional Requirements Specification"]
      - name: "Create System Architecture Document"
        role: "Architect"
        input_artifacts: ["Business Requirements Document (BRD)", "Functional Requirements Specification (FRS)", "Design Execution Plan"]
        output_artifacts: ["System Architecture Document"]
        depends_on: ["Create Design Execution Plan"]
      - name: "Create Technical Design Specification"
        role: "Architect"
        input_artifacts: ["Business Requirements Document (BRD)", "Functional Requirements Specification (FRS)", "Design Execution Plan"]
        output_artifacts: ["Technical Design Specification"]
        depends_on: ["Create System Architecture Document"]
  Build:
    description: "Implement the system based on technical design with mandatory execution planning."
    tasks:
      - name: "Create Build Execution Plan"
        role: "Developer"
        input_artifacts: ["System Architecture Document", "Technical Design Specification"]
        output_artifacts: ["Build Execution Plan"]
        depends_on: ["Create Technical Design Specification"]
      - name: "Develop Source Code"
        role: "Developer"
        input_artifacts: ["System Architecture Document", "Technical Design Specification", "Build Execution Plan"]
        output_artifacts: ["Source Code"]
        depends_on: ["Create Build Execution Plan"]
      - name: "Create Unit Test Cases"
        role: "Developer"
        input_artifacts: ["System Architecture Document", "Technical Design Specification", "Build Execution Plan"]
        output_artifacts: ["Unit Test Cases"]
        depends_on: ["Develop Source Code"]
  Validate:
    description: "Test the implemented system with mandatory execution planning."
    tasks:
      - name: "Create Validation Execution Plan"
        role: "Tester"
        input_artifacts: ["Functional Requirements Specification (FRS)", "Technical Design Specification", "Source Code"]
        output_artifacts: ["Validation Execution Plan"]
        depends_on: ["Create Unit Test Cases"]
      - name: "Create Test Plan"
        role: "Tester"
        input_artifacts: ["Functional Requirements Specification (FRS)", "Technical Design Specification", "Source Code", "Validation Execution Plan"]
        output_artifacts: ["Test Plan"]
        depends_on: ["Create Validation Execution Plan"]
      - name: "Execute Test Cases and Generate Results"
        role: "Tester"
        input_artifacts: ["Functional Requirements Specification (FRS)", "Technical Design Specification", "Source Code", "Validation Execution Plan"]
        output_artifacts: ["Test Cases and Results"]
        depends_on: ["Create Test Plan"]
  Launch:
    description: "Deploy the tested system with mandatory execution planning."
    tasks:
      - name: "Create Launch Execution Plan"
        role: "Deployer"
        input_artifacts: ["Source Code", "Test Cases and Results"]
        output_artifacts: ["Launch Execution Plan"]
        depends_on: ["Execute Test Cases and Generate Results"]
      - name: "Create Deployment Plan"
        role: "Deployer"
        input_artifacts: ["Source Code", "Test Cases and Results", "Launch Execution Plan"]
        output_artifacts: ["Deployment Plan"]
        depends_on: ["Create Launch Execution Plan"]
      - name: "Create Release Notes"
        role: "Deployer"
        input_artifacts: ["Source Code", "Test Cases and Results", "Launch Execution Plan"]
        output_artifacts: ["Release Notes"]
        depends_on: ["Create Deployment Plan"]

workflow_config:
  parallel_execution: false
