name: Deploy to Replit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Replit Deploy Hook
        run: curl -X POST "${{ secrets.REPLIT_DEPLOY_HOOK }}"
